version: "3.7"

services:
  app:
    build: .
    container_name: xDRBasedProject
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
    networks:
      - xDRBasedNetwork

  postgresdb:
    image: postgres:latest
    container_name: xDRBasedProjectDB
    environment:
      POSTGRES_DB: xdrDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - xDRBasedNetwork
    volumes:
      - pg-data:/var/lib/postgresql/data


  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=aggregatedData
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin


networks:
  xDRBasedNetwork:
    name: xDRBasedNetwork

volumes:
  pg-data: