version: "3.7"

services:
  app:
    build: .
    container_name: xDRBasedProject
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    container_name: 
    environment:
      POSTGRES_PASSWORD: pFi1DrWSaKURVQ2c4Zeu502q  
      POSTGRES_USER: admin
      POSTGRES_DB: xDR 
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
 